listen:
  - tcp://0.0.0.0:1883
  - ssl://0.0.0.0:8883
certificate:
  ca: C:\ProgramData\baetyl\cert\ca.pem
  cert: C:\ProgramData\baetyl\cert\server.pem
  key: C:\ProgramData\baetyl\cert\server.key
principals:
  - username: two-way-tls
    permissions:
      - action: 'pub'
        permit: ['tls/#']
      - action: 'sub'
        permit: ['tls/#']
  - username: test
    password: hahaha
    permissions:
      - action: 'pub'
        permit: ['#']
      - action: 'sub'
        permit: ['#']
subscriptions:
  - source:
      topic: 't'
    target:
      topic: 't/topic'
logger:
  path: C:\ProgramData\baetyl\log\service.log
  level: "debug"
